import { Inter, Philosopher } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const philosopher = Philosopher({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-philosopher",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    openGraph: {
        title: "Bryan Achmad",
        description:
            "Confide your inner thoughts and get wise advice from legends",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${philosopher.variable}`}>
                {/* <StyledComponentsRegistry>{children}</StyledComponentsRegistry> */}
                {children}
            </body>
        </html>
    );
}
